---
title: "Coding in R"
---

After the project is set up, your focus will shift to data collection and analysis. I expect that you perform your analyses in R. I don't, however, expect you to have mastered R already. These are skills that you'll develop over time - one of the best ways to learn is to analyze data you collect. You will need to have at least rudimentary R skills before you start, though, so I've put together some home brew tutorials on coding in R that cover what I see as the basics. These are just one set of resources out there that can help you learn R, brush up on what you already know, and build new skills. As discussed in [this](https://zoopecoevo.github.io/02f_code_style.html) note, your coding style is mostly up to you. You should know, however, that I primarily work with the "tidyverse", and recommend that you do too. There's an excellent resource for learning to code in R using this approach [here](https://r4ds.had.co.nz) if you want to further explore this.

As you work through these tutorials, keep in mind that the goal is to provide an introduction to R and how it can be used to work with data in this project folder workflow. This represents just the first step towards "fluency" (or even proficiency) in R. Consistent application of the material presented is required to maintain and improve your R skills. You're also encouraged to peruse projects in the ZoopEcoEvo organization in order to see code 'in action'.

# Learning Objectives

Becoming comfortable working with R takes time. These tutorials are just a first step in that direction. There are two specific learning objectives:

-   Learning Objective 1 - Achieve a level of understanding to be able to use Google to answer questions / overcome obstacles in R. This requires that you:
    -   Be able to identify your issue
    -   Know what to look for / understand what you find on Google\
-   Learning Objective 2 - Be able to modify available R scripts to analyze and visualize data sets.
    -   Understand how data structures are imported and modified
    -   Understand the functions and syntax of available scripts
